Seminar1
GO-SOPT-ANDROID/Sangwook-Woo pull request #1
Opened 2023-04-05 11:37 UTC by Sangwook123

1주차 필수과제

registerForActivityResult, putExtra활용하여 회원가입정보 저장, 스낵바메시지 출력 O
회원가입 성공조건에 부합하지않으면 회원가입 실패, 스낵바메시지 출력 O
ID,PW 일치시 로그인성공, 토스트메시지 출력 O
ID,PW 불일치시 로그인실패, 스낵바메시지 출력 O
PW 숨기기 O

2023-04-07 15:45 UTC, SeonHwan-Kim commented on app/src/main/res/layout/activity_introduce.xml
> +        android:text="이름 : "
이것도 strings에 넣어주면 좋을 것 같아요!

2023-04-07 15:45 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +                Snackbar.make(
계속 사용하는 Snackbar를 함수로 빼줘도 좋을 것 같아요!

2023-04-08 03:06 UTC, daehwan2da requested changes

2023-04-08 03:06 UTC, daehwan2da commented on app/build.gradle
> +    android {
상단에 이미 android depth 에서 관리되어지고있어서 viewBinding true 만 명시해줘도 괜찮습니다~

2023-04-08 03:06 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/IntroduceActivity.kt
> +        viewBinding.introduceTvName.text = viewBinding.introduceTvName.text.toString() + intent.getStringExtra("name")
TextView class 의 append() 를 써주면 더 간단하게 표시될것같네요~

 ```suggestion
        viewBinding.introduceTvName.append(intent.getStringExtra("name"))
```

2023-04-08 03:06 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/IntroduceActivity.kt
> +        viewBinding.introduceTvSp.text = viewBinding.introduceTvSp.text.toString() + intent.getStringExtra("special")
여기서 special 을 쓰면서 오타가 났으면 어떻게 됐을까요 🤔

ex) intent.getStringExtra("spcial")

2023-04-08 03:06 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +                n = name
음? 이 로직들은 의도하신 바가 있으실까요?

- n,s,i,p 를 선언해준 이유는?
- 위에서 n = intent.() 로 할당해주었는데, name 으로 다시한번 덮는 이유는?

2023-04-08 03:06 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/SignupActivity.kt
> +            }else if(identity.equals("") || special.equals("")){
.isBlank() 메서드를  사용해보는건 어떨까요

2023-04-09 08:04 UTC, Sangwook123 commented on app/src/main/res/layout/activity_introduce.xml
> +        android:text="이름 : "
깜빡 빼먹고 못넣었네요 지적 감사합니다!

2023-04-09 08:05 UTC, Sangwook123 commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +                Snackbar.make(
함수로 빼주면 코드가 더 간결해지겠네요 말씀감사합니다!

2023-04-10 00:35 UTC, merged